### PR TITLE
Fix Store_Setup.cs 

### LINKED ISSUE #172: [BUG] - Latest versions remove Store.Awake
I patch into this for many mods 

even some that were auga compatibile before mistlands updates 

https://github.com/RandyKnapp/Auga/blob/main/Auga/Store_Setup.cs#L19

https://github.com/RandyKnapp/Auga/blob/main/Auga/SetupHelper.cs#L22

original.gameObject.SetActive(False);
original.gameObject.name = "_inactive_PREFABNAME"

please dont just destroy the vanilla objects... just disable them.. and reassign the appropriate variables for your new scripts 

Sure its a chunk more to go through and code 

https://github.com/VMP-Valheim/InventoryOverhaul/blob/master/ModFrame/Mod.cs#L159-L202

but it will definitely retain compatibility to any mod that is patching these things

### PR DESCRIPTION
**Pull request by sbtoonz**
so that it doesn't kill StoreGui.Awake() for all other mods patching it

this resolves #172

### CODE REVIEW

**Comment by sbtoonz** [comment]
requesting review from current maintainer 
not sure if that is @RandyKnapp  or @Vapok

**Comment by Vapok** [comment]
Can you help me with just understanding.. what does this actually fix?  and so that I am aware.. how do you present the problem that this is solving?

**Comment by sbtoonz** [comment]
realistically just adding 
`if(__instance.gameObject.name.StartsWith("Auga"))return false;`

to my patch would fix this NRE 

I was trying to think of other devs in the future

**Comment by Vapok** [comment]
I've migrated these changes into my branch for the next release. Thanks for the help @sbtoonz!

**Pull request closed without merging**
